nikahmalabar/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/user/', include('user.urls')),
    path('',include('web.urls',namespace='web')), 
    path('official/',include('official.urls',namespace='official'))

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Nikah Malabar Administration"
admin.site.site_title = "Nikah Malabar Admin Portal"
admin.site.index_title = "Welcome to Nikah Malabar Admin Portal"

web/urls.py
from django.urls import path
from . import views

from django.contrib.auth import views as auth_views

app_name = 'web' 

urlpatterns = [
    path('', views.index,name="index"), 
    path('login/', views.login,name="login"),
    path('signup/', views.signup,name="signup"),
    path('profiler/', views.profiler,name="profiler"), 
    path('profilerB/', views.profilerB,name="profilerB"),
    path('imageupload/', views.imageupload,name="imageupload"),
    path('home/', views.home,name="home"),
    path('viewprofile/<int:id>', views.viewprofile,name="viewprofile"),
    path('youlike/', views.youlike,name="youlike"),
    path('match/', views.match,name="match"),
    path('pending/', views.pending,name="pending"),
    path('modify/', views.modify,name="modify"),
    path('likesyou/', views.likesyou,name="likesyou"),
    path('addphotos/', views.addphotos,name="addphotos"),
    path('myprofile/', views.myprofile,name="myprofile"), 
    path('changepass/', views.changepass,name="changepass"), 
    path('partnerpref/', views.partnerpref,name="partnerpref"), 
    path('basicpref/', views.basicpref,name="basicpref"),
    path('delete/', views.delete,name="delete"),
    path('chats/', views.chats,name="chats"),
    path('resetpass/', views.resetpass,name="resetpass"),
    path('chat-two/',views.chattwo, name='chat_two'),
    path('chat-direct/',views.chat_direct, name='chat_direct'),
]

templates/web/basicpref.html
{% extends 'web/base.html' %}
{% load static %}
{% block title %}Basic Partner Preferences{% endblock %}

{% block content %}

<style>
    .error {
        color: red;
    }
</style>







<section class="profiler">

    <div class="container">
        <div class="row profiler-head">



            <div class="col-lg-10 col-md-11 col-sm-12 col-11 pro-box">
                <div class="row text-center">
                    <div class="col-12">


                        <p class="mb-1"><span class=""></span> Basic Partner Preferences </p>
                        <h6 class="mb-3"> <b>To Find Your Perfect Match, Fill your Partner Preferences</b></h6>
                    </div>

                </div>

                <form action="" name="modify">

                    <div class="form-group row">
                        <div class="col-sm-6">
                            <label for="inputAddressLine2">Age From</label>
                            {{form.ageFrom}}
                        </div>
                        <div class="col-sm-6">
                            <label for="inputAddressLine2">Age To</label>
                            {{form.ageTo}}
                        </div>

                    </div>

                    <div class="form-group row">
                        <div class="col-sm-6">
                            <label for="inputCity">Physical Status</label>
                            {{formpro.physicalStatus}}
                        </div>

                        <div class="col-sm-6">
                            <label for="inputContactNumber">Community</label>
                            {{form.community}}
                        </div>

                    </div>
                    <div class="form-group row">
                        <div class="col-sm-6">
                            <label for="inputCity">Martial Status</label>
                            {{form.martialStatus}}
                        </div>

                        <div class="col-sm-6">
                            <label for="inputContactNumber">Complexion</label>
                            {{form.complexion}}
                        </div>

                    </div>



                    <div class="form-group row">

                        <div class="col-sm-3">
                            <label for="inputContactNumber">Height From</label>
                            <select name="heightFrom" id="heightFrom" class="required form-control">
                                <option value=0>No Preference</option>
                            </select>

                        </div>

                        <div class="col-sm-3">
                            <label for="inputContactNumber">Height To</label>
                            <select name="heightTo" id="heightTo" class="required form-control">
                                <option value=0>No Preference</option>
                            </select>

                        </div>
                        <div class="col-sm-3">
                            <label for="inputContactNumber">Weight From</label>
                            <select name="weightFrom" id="weightFrom" class="required form-control">
                                <option value=0>No Preference</option>
                            </select>
                        </div>

                        <div class="col-sm-3">
                            <label for="inputContactNumber">Weight To</label>
                            <select name="weightTo" id="weightTo" class="required form-control">
                                <option value=0>No Preference</option>
                            </select>
                        </div>

                    </div>



                    <div class="form-group row">

                        <div class="col-sm-12">
                            <label for="highestEducation">Highest Education</label>
                            {{form.education}}
                        </div>
                    </div>
                    <div class="form-group row">

                        <div class="col-sm-6">
                            <label for="highestEducation">Education Specialization</label>
                            {{form.EduSpezialization}}
                        </div>
                        <div class="col-sm-6">
                            <label for="inputContactNumber">Financial Status</label>
                            {{form.financialStatus}}
                        </div>
                    </div>

                    <div class="form-group row">

                        <div class="col-sm-12">
                            <label for="highestEducation">Present Country</label>
                            {{form.country}}
                        </div>


                    </div>
                    <div class="form-group row">
                        <div class="col-sm-6">
                            <label for="inputContactNumber">Present State</label>
                            {{form.district}}
                        </div>
                        <div class="col-sm-6">
                            <label for="highestEducation">Present City</label>
                            {{form.city}}
                        </div>


                    </div>
                    <div class="form-group row">
                        <div class="col">
                            <a href="{% url 'web:profilerB' %}"><button class="btn btn-primary px-4 save" type="button">Previous</button></a>
                        </div>

                        <div class="col text-right">
                            <button type="submit" class="btn btn-primary px-4 save">Next</button>
                        </div>
                    </div>


                </form>

            </div>
        </div>
    </div>

</section>




{% block javascript %}

<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.19.0/jquery.validate.min.js"></script>
<!-- <script src="{% static 'web/js/profiler.js' %}"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
        <script type="application/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
        <script src="{% static 'web/js/header.js' %}"></script>
        <script src="{% static 'web/js/profilecheckA.js' %}"></script>  -->
<script src="{% static 'web/js/helper.js' %}"></script>
<script src="{% static 'web/js/basicpriferenceadd.js' %}"></script>
<script>
    $(document).ready(function () {
        for (var i = 137; i <= 213; i++) {
            $('#heightTo').append("<option value=" + i + ">" + i + " cm  " + (i * 0.0328084).toFixed(1) + " ft</option>")
            $('#heightFrom').append("<option value=" + i + ">" + i + " cm  " + (i * 0.0328084).toFixed(1) + " ft</option>")
        }
        for (var i = 30; i <= 140; i++) {
            $('#weightFrom').append("<option value=" + i + ">" + i + " Kg </option>");
            $('#weightTo').append("<option value=" + i + ">" + i + " Kg </option>");
        }
    });
</script>

{% endblock %}

{% endblock %}

templates/web/changepass.html
{% extends 'web/base.html' %}
{% load static %}
{% block title %}Change Password{% endblock %}


{% block content %}
{% include "web/partials/header2.html" %}

<section class="explore pb-0">
  <div class="container">
    <div class="row exx inter">


      <div class="col-12 smsm">
        <p>Hello, Username <span><i class="icofont-hand" style="color: #cfcc1e;"></i></span></p>
      </div>
    </div>
    <div class="col-6 hrr d-none  ">

    </div>
    <div class="row inter kert justify-content-center">
      <div class="col-lg-8 col-md-10 col-sm-10 col-11 exxd">
        <ul class="d-flex justify-content-center p-0">
          <li> <a href="{% url 'web:myprofile' %}">My Profile </a></li>
          <li> <a href="{% url 'web:partnerpref' %}">Partner Preferences </a></li>
          <li> <a href="{% url 'web:addphotos' %}">Add Photos</a></li>
          <li> <a class="activee" href="{% url 'web:changepass' %}">Change Password</a></li>

        </ul>
      </div>
    </div>


  </div>
</section>





<div class="container mt-5">
  <div class="row place-content-center">

    <div class="col-lg-8">

      <form action="" name="password_reset">
        <div class="mb-3 row chanpas">
          <label for="inputPassword" class="col-lg-4 col-md-5 col-sm-6 col-form-label">Enter Old Password : </label>
          <div class="col-sm-6">
            <input type="password" class="form-control" id="inputPassword" name="inputPassword">
            <p class="error" id="error"></p>
          </div>
        </div>

        <div class="mb-3 row chanpas">
          <label for="inputPassword" class="col-lg-4 col-md-5 col-sm-6 col-form-label">Enter New Password : </label>
          <div class="col-sm-6">
            <input type="mew" class="form-control" id="newpass" name="newpass">Use a Strong password
          </div>
        </div>


        <div class="mb-3 row chanpas">
          <label for="inputPassword" class="col-lg-4 col-md-5 col-sm-6 col-form-label">Re Enter New Password : </label>
          <div class="col-sm-6">
            <input type="password" class="form-control" id="newpassconf" name="newpassconf">
          </div>
        </div>

        <div class="col-12 text-center">
          <button class="btn mt-4" type="submit">Save Changes</button>
        </div>
      </form>


    </div>

  </div>
</div>



{% include "web/partials/mobilefooter.html" %}



{% endblock %}
{% block javascript %}
<script src="{% static 'web/js/getmachedprofiles.js' %}"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.19.0/jquery.validate.min.js"></script>


<script src="{% static 'web/js/header.js' %}"></script>
<script src="{% static 'web/js/resetpassword.js' %}"></script>
{% endblock %}

templates/web/login.html
{% extends 'web/base.html' %}
{% load static %}
{% block title %}Login{% endblock %}

{% block content %}

<style>
    form .error{
        color: red;
        font-weight: 600;
    }
</style>
    
   
    
      <section class="login login-coo">
        <div class="container ">
            <div class="row">
                <div class="col-lg-5 col-md-7 col-sm-7 col-10 login-co">
                    <form action="#" name="login">
                        {% csrf_token %}
                       
                        <h3>LOGIN <span style="color: black;"><i class="icofont-login" ></i></span> </h3>
                         
                        
                        <p>Email *  </p>
                        <input id="email"  name="email" class="form-control" type="text" placeholder="Username">
                        <p id="emailwarning" class="warning"></p>
                        <p>Password * </p>
                        <input id="password1" name="password1" class="form-control" type="password" placeholder="Password">
                        <a href="{% url 'web:resetpass' %}"><p class="forgot">Forgot Username/Password ?</p></a>
                        <button id="signin_btn" class="btn btn-primary mb-2">Login Here</button>
                        <hr>
                        <a href="#" class="text-center google"> <img width="30px" src="{% static 'web/image/google.png' %}" alt=""> Signin With Google</a>
                       
                        <p class="forgot text-center">Don't have an account ?</p>
                        <a href="{% url 'web:signup' %}" ><p class="forgot text-center sign">Signup</p></a>
                    </form>

                </div>
            </div>
        </div>
      </section>




      {% block javascript %}

<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
      <!--  validation script  -->

<script src="{% static 'web/js/login.js' %}"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.19.0/jquery.validate.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
<script type="application/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>

{% endblock %}


 
    {% endblock %}

templates/web/partnerpref.html
{% extends 'web/base.html' %}
{% load static %}
{% block title %}Partner Preference{% endblock %}

{% block content %}
{% include "web/partials/header2.html" %}

<section class="explore pb-0">
  <div class="container">
    <div class="row exx inter">


      <div class="col-12 smsm">
        <p>Hello, Username <span><i class="icofont-hand" style="color: #cfcc1e;"></i></span></p>
      </div>
    </div>
    <div class="col-6 hrr d-none  ">

    </div>
    <div class="row inter kert justify-content-center">
      <div class="col-lg-8 col-md-10 col-sm-10 col-11 exxd">
        <ul class="d-flex justify-content-center p-0">
          <li> <a href="{% url 'web:myprofile' %}">My Profile </a></li>
          <li> <a class="activee" href="{% url 'web:partnerpref' %}">Partner Preferences </a></li>
          <li> <a href="{% url 'web:addphotos' %}">Add Photos</a></li>
          <li> <a href="{% url 'web:changepass' %}">Change Password</a></li>

        </ul>
      </div>
    </div>


  </div>
</section>





<div class="container mt-5 mb-80"  id="editFormDiv">
  <div class="row justify-content-right">

    <div class="col-lg-12">
      <div id="preferenceEdit">
        <form action="" name="modify">
          {% csrf_token %}
          <h4 class="preff text-center py-3">Tell Us What you Are Looking for in a Life Partner</h4>
          <div class="row">
            <div class="col-lg-6 col-md-6 mb-3">
              <div class="row proff">
                <div class="col-5">
                  <label for="">Age From</label>
                </div>
                <div class="col-6">
                  <p> <input type="number" value=0 id="ageFrom" name="ageFrom" class="form-control"> </p>
                </div>
              </div>
            </div>
  
            <div class="col-lg-6 col-md-6 mb-3">
              <div class="row proff">
                <div class="col-5"><label for="">Age To</label></div>
                <div class="col-7">
                  <p> <input type="number" value=0 id="ageTo" name="ageTo" class="form-control"> </p>
                </div>
              </div>
            </div>
  
            <div class="col-lg-6 col-md-6 mb-3">
              <div class="row proff">
                <div class="col-5"><label for="">Height From</label></div>
                <div class="col-7">
                  <p> <input type="number" value=0 id="heightFrom" name="heightFrom" class="form-control"> </p>
                </div>
              </div>
            </div>
  
            <div class="col-lg-6 col-md-6 mb-3">
              <div class="row proff">
                <div class="col-5"><label for="">Height To: </label></div>
                <div class="col-7">
                  <p> <input type="number" value=0 id="heightTo" name="heightTo" class="form-control"> </p>
                </div>
              </div>
            </div>
  
            <div class="col-lg-6 col-md-6 mb-3">
              <div class="row proff">
                <div class="col-5"><label for="">Weight From: </label></div>
                <div class="col-7">
                  <p> <input type="number" value=0 id="weightFrom" name="weightFrom" class="form-control"> </p>
                </div>
              </div>
            </div>
  
            <div class="col-lg-6 col-md-6 mb-3">
              <div class="row proff">
                <div class="col-5"><label for="">Weight To: </label></div>
                <div class="col-7">
                  <p> <input type="number" value=0 id="weightTo" name="weightTo" class="form-control"> </p>
                </div>
              </div>
            </div>
  
            <div class="col-lg-6 col-md-6 mb-3">
              <div class="row proff">
                <div class="col-5"><label for="">Martial Status : </label></div>
                <div class="col-7">
                  <p> {{form.martialStatus}} </p>
                </div>
              </div>
            </div>
  
            <div class="col-lg-6 col-md-6 mb-3">
              <div class="row proff">
                <div class="col-5"><label for="">Complexion : </label></div>
                <div class="col-7">
                  <p> {{form.complexion}} </p>
                </div>
              </div>
            </div>
  
            <div class="col-lg-6 col-md-6 mb-3">
              <div class="row proff">
                <div class="col-5"><label for="">Physical Status : </label></div>
                <div class="col-7">
                  <p> {{formpro.physicalStatus}} </p>
                </div>
              </div>
            </div>
  
            <div class="col-lg-6 col-md-6 mb-3">
              <div class="row proff">
                <div class="col-5"><label for="">Community : </label></div>
                <div class="col-7">
                  <p> {{form.community}} </p>
                </div>
              </div>
            </div>
            <div class="col-12 py-3">
            <h4 class="preff text-center">Educational & Professional Details</h4>

            </div>

            <div class="col-lg-6 col-md-6 mb-3">
              <div class="row proff">
                <div class="col-5"><label for="">Education : </label></div>
                <div class="col-7">
                  <p> {{form.education}} </p>
                </div>
              </div>
            </div>
  
            <div class="col-lg-6 col-md-6 mb-3">
              <div class="row proff">
                <div class="col-5"><label for="">Education Specialization: </label></div>
                <div class="col-7">
                  <p> {{form.EduSpezialization}} </p>
                </div>
              </div>
            </div>
  
            <div class="col-lg-6 col-md-6 mb-3">
              <div class="row proff">
                <div class="col-5"><label for="">Working with : </label></div>
                <div class="col-7">
                  <p> {{form.workingwith}} </p>
                </div>
              </div>
            </div>
  
            <div class="col-lg-6 col-md-6 mb-3">
              <div class="row proff">
                <div class="col-5"><label for="">Profession Area : </label></div>
                <div class="col-7">
                  <p> {{form.workingas}} </p>
                </div>
              </div>
            </div>
            <div class="col-12 py-3">
            <h4 class="preff text-center ">Location details</h4>

            </div>
  
            <div class="col-lg-6 col-md-6 mb-3">
              <div class="row proff">
                <div class="col-5"><label for="">Present Country : </label></div>
                <div class="col-7">
                  <p> {{form.country}} </p>
                </div>
              </div>
            </div>
  
            <div class="col-lg-6 col-md-6 mb-3">
              <div class="row proff">
                <div class="col-5"><label for="">Present District : </label></div>
                <div class="col-7">
                  <p> {{form.district}} </p>
                </div>
              </div>
            </div>
  
            <div class="col-lg-6 col-md-6 mb-3">
              <div class="row proff">
                <div class="col-5"><label for="">Present City </label></div>
                <div class="col-7">
                  <p> {{form.city}} </p>
                </div>
              </div>
            </div>
  
            <div class="col-12 text-center">
              <button class="btn mt-4">Save & Submit</button>
            </div>
          </form>
        </div>

    </div>

    <div class="col-lg-12">
      <div class="row mb-5" id="ProfileView">
        <div class="col-lg-12 py-4">
          <h4 class="preff text-center">Your Partner Preference</h4>
        </div>

        <div class="col-lg-6 col-md-6">
          <div class="row proff">
            <div class="col-5"><label for="">Age From</label></div>
            <div class="col-7">
              <p> : <b id="ageFromView"></b></p>
            </div>
          </div>
        </div>

        <div class="col-lg-6 col-md-6">
          <div class="row proff">
            <div class="col-5"><label for="">Age To</label></div>
            <div class="col-7">
              <p> : <b id="ageToView"></b></p>
            </div>
          </div>
        </div>

        <div class="col-lg-6 col-md-6">
          <div class="row proff">
            <div class="col-5"><label for="">Height From</label></div>
            <div class="col-7">
              <p> : <b id="heightFromView"></b></p>
            </div>
          </div>
        </div>

        <div class="col-lg-6 col-md-6">
          <div class="row proff">
            <div class="col-5"><label for="">Height To </label></div>
            <div class="col-7">
              <p> : <b id="heightToView"></b></p>
            </div>
          </div>
        </div>

        <div class="col-lg-6 col-md-6">
          <div class="row proff">
            <div class="col-5"><label for="">Weight From </label></div>
            <div class="col-7">
              <p> : <b id="weightFromView"></b></p>
            </div>
          </div>
        </div>

        <div class="col-lg-6 col-md-6">
          <div class="row proff">
            <div class="col-5"><label for="">Weight To </label></div>
            <div class="col-7">
              <p> : <b id="weightToView"></b></p>
            </div>
          </div>
        </div>

        <div class="col-lg-6 col-md-6">
          <div class="row proff">
            <div class="col-5"><label for="">Martial Status </label></div>
            <div class="col-7">
              <p> : <b id="martialStatusView"></b></p>
            </div>
          </div>
        </div>

        <div class="col-lg-6 col-md-6">
          <div class="row proff">
            <div class="col-5"><label for="">Complexion </label></div>
            <div class="col-7">
              <p> : <b id="complexionView"></b></p>
            </div>
          </div>
        </div>

        <div class="col-lg-6 col-md-6">
          <div class="row proff">
            <div class="col-5"><label for="">Physical Status </label></div>
            <div class="col-7">
              <p> : <b id="physicalStatusView"></b></p>
            </div>
          </div>
        </div>

        <div class="col-lg-6 col-md-6">
          <div class="row proff">
            <div class="col-5"><label for="">Community </label></div>
            <div class="col-7">
              <p> : <b id="communityView"></b></p>
            </div>
          </div>
        </div>

        <div class="col-lg-12">

          <h4 class="preff pt-4 text-center">Educational & Professional Details</h4>
        </div>

      <div class="col-lg-6 col-md-6">
        <div class="row proff">
          <div class="col-5"><label for="">Education </label></div>
          <div class="col-7">
            <p> : <b id="educationView"></b></p>
          </div>
        </div>
      </div>
      <div class="col-lg-6 col-md-6">
        <div class="row proff">
          <div class="col-5"><label for="">Education Specialization</label></div>
          <div class="col-7">
            <p> : <b id="EduSpezializationView"></b></p>
          </div>
        </div>
      </div>
      <div class="col-lg-6 col-md-6">
        <div class="row proff">
          <div class="col-5"><label for="">Working with </label></div>
          <div class="col-7">
            <p> : <b id="workingwithView"></b></p>
          </div>
        </div>
      </div>

      <div class="col-lg-6 col-md-6">
        <div class="row proff">
          <div class="col-5"><label for="">Profession Area : </label></div>
          <div class="col-7">
            <p> : <b id="workingasView"></b></p>
          </div>
        </div>
      </div>

      <div class="col-lg-12 col-12">

        <h4 class="preff text-center pt-4 ">Location details</h4>
      </div>
    
    <div class="col-lg-6 col-md-6">
      <div class="row proff">
        <div class="col-5"><label for="">Present Country </label></div>
        <div class="col-7"><p> : <b id="countryView"></b></p></div>
      </div>
    </div>

    <div class="col-lg-6 col-md-6">
      <div class="row proff">
        <div class="col-5"><label for="">Present District</label></div>
        <div class="col-7">
          <p> : <b id="districtView"></b></p>
        </div>
      </div>
    </div>

    <div class="col-lg-6 col-md-6">
      <div class="row proff">
        <div class="col-5"><label for="">Present City</label></div>
        <div class="col-7">
          <p> : <b id="cityView"></b></p>
        </div>
      </div>
    </div>
    <div class="edit-fix" onclick="editprofile()"><i class="icofont-edit-alt"></i></div>
  </div>
  </div>
  </div>


</div>

</div>
</div>



{% include "web/partials/mobilefooter.html" %}



{% endblock %}
{% block javascript %}
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.19.0/jquery.validate.min.js"></script>
<script src="{% static 'web/js/update-preference.js' %}"></script>

{% endblock %}

templates/web/resetpass.html
{% extends 'web/base.html' %}
{% load static %}
{% block title %}Reset{% endblock %}

{% block content %}

<style>
    form .error{
        color: red;
        font-weight: 600;
    }
</style>
    
   
    
      <section class="login login-coo">
        <div class="container ">
            <div class="row">
                <div class="col-lg-10 col-md-7 col-sm-7 col-10 login-co">
                    <h1>Forgotten your password?</h1>
                    <p>Enter your registered e-mail address to Reset Password.</p>
                    
                    <form action="." method="post" class="ajax">
                        <input type="email" class="form-control mb-4" name='email'>
                        

                        <input  style="width: 30%;" type="submit" class="form-control btn float-left" value="Reset">
                        <a href="{% url 'web:login' %}" style="width: 30%;" class="form-control btn float-right">Login</a>
                        {% csrf_token %}
                    </form>
                    <div class="d-none"><p class="text-danger">{{error}}</p></div> 

                </div>
            </div>
        </div>
      </section>




      {% block javascript %}

<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
      <!--  validation script  -->

<script src="{% static 'web/js/login.js' %}"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.19.0/jquery.validate.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
<script type="application/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9.15.3/dist/sweetalert2.all.min.js"></script>
<script>
    $(document).on('submit', 'form.ajax', function(e) {
        e.preventDefault();
        var $this = $(this);
        var data = new FormData(this);
        var action_url = $this.attr('action');
        var reset = $this.hasClass('reset');
        var reload = $this.hasClass('reload');
        var redirect = $this.hasClass('redirect');
        var redirect_url = $this.attr('data-redirect');

        $.ajax({
            url: action_url,
            type: 'POST',
            data: data,
            cache: false,
            contentType: false,
            processData: false,
            dataType: "json",

            success: function(data) {

                var status = data.status;
                var title = data.title;
                var message = data.message;
                var pk = data.pk;

                if (status == "true") {
                    if (title) {
                        title = title;
                    } else {
                        title = "Success";
                    }

                    Swal.fire({
                        title: title,
                        html: message,
                        icon: 'success',
                    }).then(function() {
                        if (redirect) {
                            window.location.href = redirect_url;
                        }
                        if (reload) {
                            window.location.reload();
                        }
                        if (reset) {
                            window.location.reset();
                        }
                    });

                } else {
                    if (title) {
                        title = title;
                    } else {
                        title = "An Error Occurred";
                    }
                    Swal.fire({
                        title: title,
                        html: message,
                        icon: "error"
                    });

                }
            },
            error: function(data) {
                var title = "Couldn't Find Record";
                var message = "User with email not found";
                Swal.fire({
                    title: title,
                    html: message,
                    icon: "error"
                });
            }
        });
    });
</script>


{% endblock %}


 
    {% endblock %}