nikahmalabar/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/user/', include('user.urls')),
    path('',include('web.urls',namespace='web')), 
    path('official/',include('official.urls',namespace='official'))

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Nikah Malabar Administration"
admin.site.site_title = "Nikah Malabar Admin Portal"
admin.site.index_title = "Welcome to Nikah Malabar Admin Portal"

web/urls.py
from django.urls import path
from . import views

from django.contrib.auth import views as auth_views

app_name = 'web' 

urlpatterns = [
    path('', views.index,name="index"), 
    path('login/', views.login,name="login"),
    path('signup/', views.signup,name="signup"),
    path('profiler/', views.profiler,name="profiler"), 
    path('profilerB/', views.profilerB,name="profilerB"),
    path('imageupload/', views.imageupload,name="imageupload"),
    path('home/', views.home,name="home"),
    path('viewprofile/<int:id>', views.viewprofile,name="viewprofile"),
    path('youlike/', views.youlike,name="youlike"),
    path('match/', views.match,name="match"),
    path('pending/', views.pending,name="pending"),
    path('modify/', views.modify,name="modify"),
    path('likesyou/', views.likesyou,name="likesyou"),
    path('addphotos/', views.addphotos,name="addphotos"),
    path('myprofile/', views.myprofile,name="myprofile"), 
    path('changepass/', views.changepass,name="changepass"), 
    path('partnerpref/', views.partnerpref,name="partnerpref"), 
    path('basicpref/', views.basicpref,name="basicpref"),
    path('delete/', views.delete,name="delete"),
    path('chats/', views.chats,name="chats"),
    path('resetpass/', views.resetpass,name="resetpass"),
    path('chat-two/',views.chattwo, name='chat_two'),
    path('chat-direct/',views.chat_direct, name='chat_direct'),
]

templates/web/partials/fatheroccupation.html
{% load static %}




{% comment %} (('House Wife','House Wife'),('Doctor','Doctor'),('Engineer','Engineer'),('Manager','Manager'),('Pharmacist','Pharmacist'),('Accountant','Accountant'),('Teacher','Teacher'),('Late','Late'),('Private','Private'),('Self Employee','Self Employee'),('NRI','NRI'),('Home Maker','Home Maker'),('Govt Employee','Govt Employee'),('Retired','Retired'),('Buisness','Buisness'),('Coolie','Coolie'),('Farmer','Farmer'),('Others','Others')) {% endcomment %}

<select id='fatherOccupation' name='fatherOccupation' class="form-control">
    <option value="Private">Private</option>
    <option value="Self Employee">Self Employee</option>
    <option value="Doctor">Doctor</option>
    <option value="Engineer">Engineer</option>
    <option value="Manager">Manager</option>
    <option value="Pharmacist">Pharmacist</option>
    <option value="Accountant">Accountant</option>
    <option value="Teacher">Teacher</option>
    <option value="Late">Late</option>
    <option value="NRI">NRI</option>
    <option value="Home Maker">Home Maker</option>
    <option value="Govt Employee">Govt Employee</option>
    <option value="Retired">Retired</option>
    <option value="Buisness">Buisness</option>
    <option value="Coolie">Coolie</option>
    <option value="Farmer">Farmer</option>
    <option value="Other">Other</option>
</select>

templates/web/partials/footer.html
{% load static %}

<footer class="d-none d-lg-block">
    <img class="fooo d-none d-lg-block" style="position:absolute; width: 100%;" src="{% static 'web/image/footer.png' %}" alt="">
    
    <div style="position: relative;" class="container" id="foote">
        <div class="row justify-content-center footer-down">
            <h3>Get started with the mobile app!</h3>
            <p>Find your perfect mate now faster and easier in our mobile app. Download free from play store or Apple Store.</p>
            <div class="play">
                <img src="{% static 'web/image/android.png' %}" alt="">
                <img src="{% static 'web/image/ios.png' %}" alt="">
            </div>
        </div>
       
    </div>
    <div class="container-fluid foo">
    <div class="row text-center">
        <div class="col-lg-3 col-6 footer-list align-self-center">
            <img class="" width="100%" src="{% static 'web/image/logor.png' %}" alt="logo">
        </div>
        <div class="col-lg-3 col-6 footer-list">
            <ul>
                <li> <h2>NAVIGATE</h2> </li>
                <li><a href="#">HOME</a></li>
                <li><a href="#">ABOUT US</a></li>
                <li><a href="#">LOGIN</a></li>
                <li><a href="#">REGISTER</a></li>
                
            </ul>
        </div>
        <div class="col-lg-3 col-6 footer-list">
            <ul>
                <li> <h2>ASSISTANCE</h2> </li>
                <li><a href="#">BLOG</a></li>
                <li><a href="#">SUPPORT</a></li>
                <li><a href="#">TERMS AND CONDITIONS</a></li>
                <li><a href="#">PRIVACY POLICY</a></li>
                
            </ul>
        </div>
        <div class="col-lg-3 col-6 footer-list">
            <ul>
                <li> <h2>FOLLOW US</h2> </li>
                <li><a href="#">FACEBOOK</a></li>
                <li><a href="#">INSTAGRAM</a></li>
                <li><a href="#">TWITTER</a></li>
                
            </ul>
        </div>
    </div>

    <!-- <div class="row text-center pt-3 social">
        <div class="col-12"  id="footer">
            <ul class="d-flex">
                <li><i class="icofont-youtube"></i></li>
                <li><i class="icofont-twitter"></i></li>
                <li><i class="icofont-facebook"></i></li>
            </ul>
        </div>
    </div> -->

        <div class="row justify-content-center copy" >
            <p>© Copyright Nikah Malabar. All Rights Reserved</p>
            
        </div>

    </div>

</footer>

templates/web/partials/header.html
{% load static %}

<header id="header" class="fixed-top headr">
  <div class="container-fluid d-flex justify-content-between place-items-center">

    <a href="{% url 'web:index' %}"><img class="logo-img" src="{% static 'web/image/logo.png' %}"  alt=""></a>

    
    {% if is_index %}

    <div class="ribtns pr-5" id="username" >
      <span style="color: black;"> <span class="phone-sign">Already a member?</span><a class="news ml-4" href="{% url 'web:login' %}">Sign in</a></span> 
    </div>

    
    
    {% endif %}

    

  </div>

  </div>
</header> 
<!-- End Header -->

templates/web/partials/header2.html
{% load static %}
<header id="header" class="fixed-top deaser">
  <div class="container d-flex align-items-center justify-content-between">

    <h1 class="logo"><a href="{% url 'web:home' %}"><img src="{% static 'web/image/logor.png' %}" alt=""></a></h1>

    <!-- <div class="form-group has-search m-0">
      <span class="icofont-search form-control-feedback"></span>
      <input type="text" class="form-control" placeholder="Search" id="searchbox">
    </div> -->
    <div class="d-none d-sm-blockk" id="imagecli">
      <span class="icofont-navigation-menu form-control-feedback"></span>
    </div>

    

    <nav class="nav-menu d-none d-lg-block iconn">
      <ul class="place-items-center">
        <li class="active"><a href="{% url 'web:home' %}"><i class="icofont-binoculars text-white mr-2"></i>Explore</a></li>
        <li><a href="{% url 'web:chat_direct' %}"><i class="icofont-ui-text-chat mr-2"></i>Chat</a></li>

        <li><a href="/youlike"><span id="intr" class="ml-0 favv">0</span><i class="icofont-ui-love-add mr-2"></i>Interests</a></li>


        <li>
          <a id="usernamefield1" class="uder " data-toggle="" href="#features"></a>
          
        </li>


      </ul>
    </nav><!-- .nav-menu -->


    <div class="position-fixed mob-hedr" id="mob-hedrr">

      <img width="40px" id="mobilemenuImage" height="40px" alt="">
      <span id="mobileName">Muhammed Niyas</span> <span><i id="closed" style="font-weight: 600;" class="icofont-close-circled float-right"></i> </span>
      <ul>

        <li><a href="{% url 'web:myprofile' %}" class="link">My Profile<span class="float-right"><i class="icofont-arrow-right"></i></span> </a></li>
        <li><a href="{% url 'web:partnerpref' %}" class="link">Partner Preferences<span class="float-right"><i class="icofont-arrow-right"></i></span> </a></li>
        <li><a href="{% url 'web:addphotos' %}" class="link">Edit Photo<span class="float-right"><i class="icofont-arrow-right"></i></span> </a></li>
        <li><a href="{% url 'web:modify' %}" class="link">Advance Search<span class="float-right"><i class="icofont-arrow-right"></i></span> </a></li>
        <li><a href="{% url 'web:delete' %}" class="link">Delete Account<span class="float-right"><i class="icofont-arrow-right"></i></span> </a></li>
       
        <li class="color-redd"><a id="logout" href="#" class="link color-red">Logout<span class="float-right"><i class="icofont-power color-red"></i></span> </a></li>
        
      </ul>
    </div>




  </div>
</header><!-- End Header -->
  

<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="{% static 'web/js/loadheader.js' %}"></script>
<script src="{% static 'web/js/getprofiles.js' %}"></script>

<script>

  $(document).ready(function () {
    loadlikecount();
    $('#searchbox').keyup(function (e) {
      getdatas($('#searchbox').val());
    });

  });
</script>

<script>
  $("#imagecli").click(function(){
  $("#mob-hedrr").fadeIn();
});


$('#closed').on('click', function(){
  $("#mob-hedrr").fadeOut();
})
// $("#show").click(function(){
//   $("p").show();
// });
</script>

templates/web/partials/interestheader.html
{% load static %}


    <section class="explore pb-0">
      <div class="container">
          <div class="row exx inter">
              
              
              <div class="col-12 smsm">
                <p> <span><i class="icofont-ui-love-add" style="color: #00AB3B;"></i></span> Interests</p> 
              </div>

              <div class="col-6 hrr">

              </div>

              <div class="col-12">
                  <ul class="d-flex">
                     <li >  <a class="{% if is_likesyou %}activee{% endif %}" href="{% url 'web:likesyou' %}">Likes You<span id="likyo" class="ml-0 lik-numb">0</span></a></li>
                     <li>  <a class="{% if is_match %}activee{% endif %}" href="{% url 'web:match' %}">Match<span id="matchh" class="ml-0 lik-numb">0</span></a></li>
                     <li>  <a class="{% if is_youlike %}activee{% endif %}" href="{% url 'web:youlike' %}">You Like<span id="youlik" class="ml-0 lik-numb">0</span></a></li>
                     
                  </ul>
              </div>
          </div>
          
      </div>
    </section>

templates/web/partials/mobilefooter.html
{% load static %}
<div class="container-fluid d-none" id="chatnav" >
    <div class="row">
        <div class="col-sm-12">
            <nav class="nav-menu iconn">
                <ul class="plac">
                  <li><a href="{% url 'web:chat_direct' %}"><i class="icofont-ui-text-chat mr-2"></i></a></li>
                  <li class="{% if is_home %}active{% endif %}"><a href="{% url 'web:home' %}"><i class="icofont-binoculars mr-2"></i></a></li>
                  <li class="{% if is_youlike %}active{% endif %}"> <a href="{% url 'web:youlike' %}"><i class="icofont-ui-love-add mr-2"></i></a></li>
                  
                  

                </ul>
              </nav>
        </div>
    </div>
</div>

templates/web/partials/motherocupation.html
{% load static %}


{% comment %} (('House Wife','House Wife'),('Doctor','Doctor'),('Engineer','Engineer'),('Manager','Manager'),('Pharmacist','Pharmacist'),('Accountant','Accountant'),('Teacher','Teacher'),('Late','Late'),('Private','Private'),('Self Employee','Self Employee'),('NRI','NRI'),('Home Maker','Home Maker'),('Govt Employee','Govt Employee'),('Retired','Retired'),('Buisness','Buisness'),('Coolie','Coolie'),('Farmer','Farmer'),('Others','Others')) {% endcomment %}

<select id='motherOccupation' name='motherOccupation' class="form-control">
    <option value="Private">House Wife</option>
    <option value="Self Employee">Self Employee</option>
    <option value="Doctor">Doctor</option>
    <option value="Engineer">Engineer</option>
    <option value="Manager">Manager</option>
    <option value="Pharmacist">Pharmacist</option>
    <option value="Accountant">Accountant</option>
    <option value="Teacher">Teacher</option>
    <option value="Late">Late</option>
    <option value="Private">Private</option>
    <option value="NRI">NRI</option>
    <option value="Home Maker">Home Maker</option>
    <option value="Govt Employee">Govt Employee</option>
    <option value="Retired">Retired</option>
    <option value="Buisness">Buisness</option>
    <option value="Coolie">Coolie</option>
    <option value="Farmer">Farmer</option>
    <option value="Other">Other</option>
</select>

templates/web/partials/selectedu.html
{% load static %}






<select id='EduSpezialization' class="form-control">


    <option value="MBBS">MBBS</option>
    <option value="BDS">BDS</option>
    <option value="BAMS">BAMS</option>
    <option value="BUMS">BUMS</option>
    <option value="B.Sc Nursing">B.Sc Nursing</option>
    <option value="B.Pharm">B.Pharm</option>
    <option value="M.Pharm">M.Pharm</option>
    <option value="D.Pharm">D.Pharm</option>
    <option value="B.Arch">B.Arch</option>
    <option value="M.Arch">M.Arch</option>
    <option value="Bachelor of Arts">Bachelor of Arts</option>
    <option value="Bachelor of Science">Bachelor of Science</option>
    <option value="Bachelor of Fine Art">Bachelor of Fine Art</option>
    <option value="Master of Arts">Master of Arts</option>
    <option value="Master of Science">Master of Science</option>
    <option value="B.A English">B.A English</option>
    <option value="B.A History">B.A History</option>
    <option value="B.A Economics">B.A Economics</option>
    <option value="B.A Psychology">B.A Psychology</option>
    <option value="B.A Journalism">B.A Journalism</option>
    <option value="B.A Arabic">B.A Arabic</option>
    <option value="B.A Political Science">B.A Political Science</option>
    <option value="B.A (Honors)">B.A (Honors)</option>
    <option value="M.A English">M.A English</option>
    <option value="M.A History">M.A History</option>
    <option value="M.A Economics">M.A Economics</option>
    <option value="M.A Arabic">M.A Arabic</option>
    <option value="M.A Malayalam">M.A Malayalam</option>
    <option value="B.Sc in Computer Science">B.Sc in Computer Science</option>
    <option value="B.Sc Physics">B.Sc Physics</option>
    <option value="B.Sc Mathematics">B.Sc Mathematics</option>
    <option value="B.Sc Botany">B.Sc Botany</option>
    <option value="B.Sc in Zoology">B.Sc in Zoology</option>
    <option value="B.Sc in Statistics">B.Sc in Statistics</option>
    <option value="M.Sc in Computer Science">M.Sc in Computer Science</option>
    <option value="M.Sc Physics">M.Sc Physics</option>
    <option value="M.Sc Mathematics">M.Sc Mathematics</option>
    <option value="B.Sc Botany">B.Sc Botany</option>
    <option value="M.Sc in Zoology">M.Sc in Zoology</option>
    <option value="M.Sc in Statistics">M.Sc in Statistics</option>
    <option value="B.com">B.com</option>
    <option value="M.com">M.com</option>
    <option value="BBA">BBA</option>
    <option value="MBA">MBA</option>
    <option value="Chartered Accountant (CA)">Chartered Accountant (CA)</option>
    <option value="Company Secretary (CS)">Company Secretary (CS)</option>
    <option value="LLB">LLB</option>
    <option value="B.Tech">B.Tech</option>
    <option value="M.Tech">M.Tech</option>
    <option value="B.Tech Mechanical">B.Tech Mechanical</option>
    <option value="B.Tech Civil">B.Tech Civil</option>
    <option value="B.Tech Computer Science and Engineering">B.Tech Computer Science and Engineering</option>
    <option value="B.Tech ECE">B.Tech ECE</option>
    <option value="B.Tech Aerospace">B.Tech Aerospace</option>
    <option value="Diploma Courses">Diploma Courses</option>
    <option value="Certificate Couses">Certificate Couses</option>
    <option value="Diploma in Interior Designing">Diploma in Interior Designing</option>
    <option value="Diploma in Fashion Designing">Diploma in Fashion Designing</option>
    <option value="Hotel Management">Hotel Management</option>
    <option value="Animation, Graphics and Multimedia">Animation, Graphics and Multimedia</option>
    <option value="ITI">ITI</option>
    <option value="Higher Secondary">Higher Secondary</option>
    <option value="High School">High School</option>
    <option value="M. Ed">M. Ed</option>
    <option value="B. Ed">B. Ed</option>
    <option value="TTC">TTC</option>
    <option value="Other">Other</option>
    

</select>

templates/web/partials/workingas.html
{% load static %}






<select id='workingas' class="form-control">


    <option value="Not Working">Not Working</option>
    <option value="Accountant">Accountant</option>
    <option value="CA">CA</option>
    <option value="BUMS">BUMS</option>
    <option value="Secretary">Secretary</option>
    <option value="Doctor">Doctor</option>
    <option value="Manager">Manager</option>
    <option value="Asst. Manager">Asst. Manager</option>
    <option value="Engineer">Engineer</option>
    <option value="Bank employee">Bank employee</option>
    <option value="PRO">PRO</option>
    <option value="Sales">Sales</option>
    <option value="Electrician">Electrician</option>
    <option value="Mechanic">Mechanic</option>
    <option value="Plumber">Plumber</option>
    <option value="Coolie">Coolie</option>
    <option value="Cashier">Cashier</option>
    <option value="Driver">Driver</option>
    <option value="Consultants">Consultants</option>
    <option value="Nurse">Nurse</option>
    <option value="Marketing Executive">Marketing Executive</option>
    <option value="HRM">HRM</option>
    <option value="Pharmacist">Pharmacist</option>
    <option value="Self Employed">Self Employed</option>
    <option value="Part-Time">Part-Time</option>
    <option value="Professor">Professor</option>
    <option value="Teacher">Teacher</option>

    <option value="Software Developer">Software Developer</option>
    <option value="Graphics Designer">Graphics Designer</option>
    <option value="Business">Business</option>
    <option value="Administrator">Administrator</option>
    <option value="Other">Other</option>
    

</select>